### ISSUE TITLE
certbot not recognizing authenticator

### ISSUE THREAD

**Issue by CaptainFrosty** [alexzorin/certbot-dns-multi#4]
Hi, I installed certbot from the Rocky Linux repos, and both it and the plugin are listed in pip but it keeps telling me the authenticator is unknown. All my certbot files are in `/usr/lib/python3.9/site-packages` and the plugin files are in `/usr/local/lib64/python3.9/site-packages`. Certbot version is 2.6.0.

**Comment by alexzorin** [comment]
This sounds like the same issue as the EPEL9 package: https://community.letsencrypt.org/t/how-do-i-make-certbot-find-use-an-installed-plugin/198647/18

If so, you won't be able to mix the RPM and the pip package. You'll need to use the Certbot pip or snap instructions rather than the EPEL package.

**Comment by CaptainFrosty** [comment]
Ah, I see. It may be the same package as I have EPEL repos as well.

**Comment by CaptainFrosty** [comment]
@alexzorin I don't really get why there would be any problem created by using an RPM, if it shows up in pip all the same, but I am not an expert. Does it need the python venv for some reason? I used the snap for a good while, but after looking into snap some I removed it since apparently on RHEL-based distros in particular it is not very secure due to the lack of Apparmor for some reason.

**Comment by alexzorin** [comment]
It's not really about whether it's RPM or pip. 

The maintainers of the Certbot package for EPEL9 decided to use `python -s`, which prevents Python from loading any "user packages" (i.e. those installed in `/usr/local/`). If you install a package using `pip`, that's exactly where it goes.

I don't know why they decided to do this, we didn't suggest it and as far as I know, no other distributions do it either.

If you don't want to use snap, my suggestion is to use https://certbot.eff.org/instructions?ws=other&os=pip&tab=wildcard instead of the EPEL9 Certbot package.
